POST http://localhost:3000/api/heroes HTTP/1.1
Content-Type: application/json

{
    "nickname": "Hulk",
    "realName": "Ро́берт Брюс Бэ́ннер",
    "originDescription": "супергерой комиксов издательства Marvel Comics",
    "cathPhrase": "I am Hulk",
    "superpower": ["flying"]

}

    # "nickname": "Spider",
    # "realName": "Пи́тер",
    # "originDescription": "Паркер изображён как ученик Мидтаунской школы науки и технологий, который получил способности после укуса радиоактивного паука и с тех пор тайно действовал как линчеватель. В 2016 году Питер был завербован Тони Старком (Железным человеком) для противостояния Стиву Роджерсу (Капитану Америке).",
    # "cathPhrase": "I am Spider Man",
    # "superpower": ["flying"]

#     "superpower": ["running"]

# {
#     "nickname": "Spider",
#     "realName": "Пи́тер",
#     "originDescription": "Паркер изображён как ученик Мидтаунской школы науки и технологий, который получил способности после укуса радиоактивного паука и с тех пор тайно действовал как линчеватель. В 2016 году Питер был завербован Тони Старком (Железным человеком) для противостояния Стиву Роджерсу (Капитану Америке).",
#     "cathPhrase": "I am Spider Man",
#     "superpower": ["flying", "jumping"]
# }




# "id": 1,
#     "nickname": "Thor",
#     "realName": "Тор О́динсон",
#     "originDescription": "Тор — один из самых могущественных Асгардцев древней инопланетной цивилизации с давними связями с Землёй, которых люди считают Богами. Тор владеет мощным молотом Мьёльнир и изначально изображается как высокомерный наследник трона Асгарда, чьё дерзкое поведение вызывает беспорядки среди Девяти миров, находящихся под защитой Асгарда, в результате чего он вступает в конфликт со своим приёмным братом Локи. Тор берёт на себя обязательство защищать Землю и становится участником команды «Мстителей». После смерти Одина, Тор становится королём Асгарда, однако освободившаяся сестра Тора Хела заставляет его выпустить Суртура, чтобы он уничтожил Асгард. После скачка Тор передаёт корону Нового Асгарда Валькирии и присоединяется к Стражам Галактики.",
#     "cathPhrase": "...Now They're But Humble Tools For Peace",
#     "createdAt": "2022-12-28T13:24:43.637Z",
#     "updatedAt": "2022-12-28T13:24:43.637Z"
#   },
#   {
#     "id": 2,
#     "nickname": "Iron Man",
#     "realName": "Tony Stark",
#     "originDescription": "Богатый, красивый, ходит в красном костюме",
#     "cathPhrase": "I am Iron Man",
#     "createdAt": "2022-12-28T13:38:32.972Z",
#     "updatedAt": "2022-12-28T13:38:32.972Z"
#   },
#   {
#     "id": 7,
#     "nickname": "Hulk",
#     "realName": "Ро́берт Брюс Бэ́ннер ",
#     "originDescription": "супергерой комиксов издательства Marvel Comics.",
#     "cathPhrase": "I am Hulk",
#     "createdAt": "2022-12-29T08:21:16.768Z",
#     "updatedAt": "2022-12-29T08:21:16.768Z"
#   },
#
#   {
#     "id": 9,
#     "nickname": "Spider-Man",
#     "realName": "Пи́тер Па́ркер",
#     "originDescription": "Паркер изображён как ученик Мидтаунской школы науки и технологий, который получил способности после укуса радиоактивного паука и с тех пор тайно действовал как линчеватель. В 2016 году Питер был завербован Тони Старком (Железным человеком) для противостояния Стиву Роджерсу (Капитану Америке).",
#     "cathPhrase": "I am Spider Man",
#     "createdAt": "2022-12-29T08:54:24.500Z",
#     "updatedAt": "2022-12-29T08:54:24.500Z"
#   },
#   {
#     "id": 11,
#     "nickname": "BlackWidow",
#     "realName": "Ната́лья Альяновна Ро́манова",
#     "originDescription": "Изначально, Наташа Романофф изображена как русская шпионка и опытный боец рукопашного боя, обученная с детства в специальной академии «Красная комната». В конце концов она присоединяется к контртеррористическому агентству «Щ.И.Т.» и становится ключевым членом команды «Мстители». Когда Танос испепеляет половину жизни во Вселенной, Наташа становится лидером команды «Мстители». Наташа, вместе со Стивом Роджерсом собирает команду вновь и отменяет действия Таноса, пожертвовав собственной жизнью ради получения одного из Камней Бесконечности — Камня Души.",
#     "cathPhrase": "I am Black Widow",
#     "createdAt": "2022-12-29T09:29:14.442Z",
#     "updatedAt": "2022-12-30T12:38:07.671Z"
#   }