PUT http://localhost:3000/api/heroes/3 HTTP/1.1
Content-Type: application/json

{
    "nickname": "Batman",
    "realName": "Брюс Уэйн",
    "originDescription": "супергерой комиксов издательства Marvel Comics / DC Comics.",
    "cathPhrase": "I am Batmanl",
    "superpower": ["Эхолокация"]

  
}

#    "nickname": "Флэш",
#     "realName": "Барт Аллен",
#     "originDescription": "супергерой комиксов издательства Marvel Comics / DC Comics.",
#     "cathPhrase": "I am Флэш",
#     "superpower": ["flying"]

#   "superpower": ["flying"]
